### ISSUE TITLE
Issue with Mac 'Carriage Return' in getLineEnd

### ISSUE THREAD

**Issue by ladome** [apurin/line-navigator#11]
The following code doesn't work with Mac format file: (only CR character)

```
    // searches for line end, which can be \r\n (Windows) or \n (Unix)
    // returns line end postion including all line ending
    LineNavigator.prototype.getLineEnd = function (buffer, start, end, isEof) {
        var newLineCode = '\n'.charCodeAt(0);
        var caretReturnCode = '\r'.charCodeAt(0);

        for (var i = start; i < end; i++) {
            if (buffer[i] === newLineCode) {                
                if (i !== end && buffer[i + 1] === 0) {
                    return i + 1; // it is UTF16LE and trailing zero belongs to \n
                } else {
                    return i;
                }
            }
        }
    }

```
[testfile.txt](https://github.com/anpur/line-navigator/files/1115347/testfile.txt)

**Comment by anpur** [comment]
Hi Ladome,

`CR` line breaks were only used in the classical MacOS before MacOS X was introduced, that was 16 years ago :) 
No modern systems use CR as line breaks: https://en.wikipedia.org/wiki/Newline#Representations
Namely such line breaks were used in Commodore 8-bit machines, Acorn BBC, ZX Spectrum, TRS-80, Apple II family, Oberon, the classic Mac OS up to version 9, MIT Lisp Machine and OS-9.
Also there was `LFCR` line breaks in even more exotic systems.

I realise that even after systems are gone some files are still left. But I've found that recognising it in automatic manner (which is always nice) makes this logic too complicated. 

You still can checkout commit 102aadcad111a75a1baf267f99037174607e4a56, which had `CR`  support but had bug for `UTF16LE`.
